/* TIMER 0 WITHOUT INTERRUPT */
#include<htc.h>
void delay_ms()
{
	T0CS=0;   //TIMER ZERO SELECT FOR CLOCK SOURCE
	/* TO SELECT PRESCALAR BITS WHICH ENABLES 1:32 COUNT */
	PS2=1;
	PS1=0;
	PS0=0;
	TMR0IF=0; 
	TMR0=224; //LOAD TIMER TO BRING 31 CYCLES
	while(TMR0IF==0); //POLLING ON TMR0IF FLAG
	TMR0IF=0;
}
int main()
{
	TRISB=TRISC=TRISD=0X00;
	while(1)
	{
		PORTB=PORTC=PORTD=0X00;
		delay_ms();
		PORTB=PORTC=PORTD=0XFF;
		delay_ms();
	}
}